[package]
name = "tester-contract"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false
license = "GPL-3.0-only"

[lib]
path = "src/lib.rs"

[dependencies]
multiversx-sc = "=0.43.3"

[dev-dependencies]
multiversx-sc-scenario = "=0.43.3"

[package.metadata.release]
release = false
