[package]
name = "contract-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.tester-contract]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.3"
default-features = false
