[package]
name = "tester-contract-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies]
multiversx-sc-meta = { path = "../../../../mx-sdk-rs/framework/meta" }
tester-contract = { path = ".." }

[package.metadata.release]
release = false


