[package]
name = "novax-cookbook-deps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
novax = "0.0.22"
novax-caching = "0.0.22"
novax-mocking = "0.0.2"
tokio = "1.32.0"
num-bigint = "0.4.4"
async-trait = "0.1.73"
serde = "1.0.188"

[package.metadata.release]
release = false

