[package]
name = "novax-executor"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0-only"
description = "Part of the NovaX framework, this crate facilitates the execution of transactions and queries against smart contracts on the blockchain."
repository = "https://github.com/gfusee/novax"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.29.1"
async-trait = "0.1.73"
num-bigint = "0.4.3"
serde = "1.0.183"
hex = "0.4.3"
base64 = "0.21.3"
novax-data = { path = "../data" }
multiversx-sc = "0.43.2"
multiversx-sc-scenario = "0.43.2"
multiversx-sdk = "0.2.0"
multiversx-sc-snippets = "0.43.2"