name: Publish crates

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Switch to Rust nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --features ci
    - name: Run tests
      run: cargo test --features ci
    - name: Install cargo-release
      run: cargo install cargo-release
    - name: Publish crate
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      run: yes | cargo-release release ${{ github.event.release.tag_name }} --execute --no-tag --no-verify --allow-branch \*
